### ISSUE TITLE
Publish Markdown component with CSS styles for apps with webpack workflow

### ISSUE THREAD

**Issue by sergeyt** [reactbits/markdown#3]
https://github.com/react-toolbox/react-toolbox uses this approach

**Comment by Martin-Pitt** [comment]
I'm getting errors to some unknown syntax when trying to use this component, believe it is related to this issue.

```
ERROR in ./~/react-markdown2/lib/style.scss
Module parse failed: /Users/martin/Projects/foobar/node_modules/react-markdown2/lib/style.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp.raise (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.parseExprAtom (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:330:12)
    at Parser.pp.parseExprSubscripts (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOps (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseStatement (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:1753:23)
 @ ./~/react-markdown2/lib/embed.js 29:13-36

ERROR in ./~/react-markdown2/lib/editor/style.scss
Module parse failed: /Users/martin/Projects/foobar/node_modules/react-markdown2/lib/editor/style.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp.raise (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.getTokenFromCode (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:2813:8)
    at Parser.pp.readToken (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:2508:15)
    at Parser.pp.nextToken (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:2500:71)
    at Parser.parse (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:1615:10)
    at Object.parse (/Users/martin/Projects/foobar/node_modules/acorn/dist/acorn.js:882:44)
    at Parser.parse (/Users/martin/Projects/foobar/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/martin/Projects/foobar/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/martin/Projects/foobar/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/martin/Projects/foobar/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/react-markdown2/lib/editor/editor.js 30:13-36
```

**Comment by sergeyt** [comment]
@Martin-Pitt now you have to configure webpack to handle `.scss` files in your app. For example see https://github.com/reactbits/devpack/blob/master/webpack.js. Also see https://github.com/reactbits/markdown/blob/master/webpack.config.js to handle raphael errors.
